//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.832.
// 
#pragma warning disable 1591

namespace myApp.ClientDAL.WSOrdrelinjeDAL {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Collections.Generic;
    using myApp.Model;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OrdrelinjeDALSoap", Namespace="http://tempuri.org/")]
    public partial class OrdrelinjeDAL : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getOrdrelinjerOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOrdrelinjeOperationCompleted;
        
        private System.Threading.SendOrPostCallback nyOrdrelinjeOperationCompleted;
        
        private System.Threading.SendOrPostCallback slettOrdrelinjeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOrdrelinjerFraBrukernavnOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OrdrelinjeDAL() {
            this.Url = global::myApp.ClientDAL.Properties.Settings.Default.MyApp_ClientDAL_WSOrdrelinjeDAL_OrdrelinjeDAL;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getOrdrelinjerCompletedEventHandler getOrdrelinjerCompleted;
        
        /// <remarks/>
        public event getOrdrelinjeCompletedEventHandler getOrdrelinjeCompleted;
        
        /// <remarks/>
        public event nyOrdrelinjeCompletedEventHandler nyOrdrelinjeCompleted;
        
        /// <remarks/>
        public event slettOrdrelinjeCompletedEventHandler slettOrdrelinjeCompleted;
        
        /// <remarks/>
        public event getOrdrelinjerFraBrukernavnCompletedEventHandler getOrdrelinjerFraBrukernavnCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOrdrelinjer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public List<Ordrelinje> getOrdrelinjer(int ordreID) {
            object[] results = this.Invoke("getOrdrelinjer", new object[] {
                        ordreID});
            return ((List<Ordrelinje>)(results[0]));
        }
        
        /// <remarks/>
        public void getOrdrelinjerAsync(int ordreID) {
            this.getOrdrelinjerAsync(ordreID, null);
        }
        
        /// <remarks/>
        public void getOrdrelinjerAsync(int ordreID, object userState) {
            if ((this.getOrdrelinjerOperationCompleted == null)) {
                this.getOrdrelinjerOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOrdrelinjerOperationCompleted);
            }
            this.InvokeAsync("getOrdrelinjer", new object[] {
                        ordreID}, this.getOrdrelinjerOperationCompleted, userState);
        }
        
        private void OngetOrdrelinjerOperationCompleted(object arg) {
            if ((this.getOrdrelinjerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOrdrelinjerCompleted(this, new getOrdrelinjerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOrdrelinje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Ordrelinje getOrdrelinje(int ordrelinjeID) {
            object[] results = this.Invoke("getOrdrelinje", new object[] {
                        ordrelinjeID});
            return ((Ordrelinje)(results[0]));
        }
        
        /// <remarks/>
        public void getOrdrelinjeAsync(int ordrelinjeID) {
            this.getOrdrelinjeAsync(ordrelinjeID, null);
        }
        
        /// <remarks/>
        public void getOrdrelinjeAsync(int ordrelinjeID, object userState) {
            if ((this.getOrdrelinjeOperationCompleted == null)) {
                this.getOrdrelinjeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOrdrelinjeOperationCompleted);
            }
            this.InvokeAsync("getOrdrelinje", new object[] {
                        ordrelinjeID}, this.getOrdrelinjeOperationCompleted, userState);
        }
        
        private void OngetOrdrelinjeOperationCompleted(object arg) {
            if ((this.getOrdrelinjeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOrdrelinjeCompleted(this, new getOrdrelinjeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/nyOrdrelinje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void nyOrdrelinje(Ordrelinje ol) {
            this.Invoke("nyOrdrelinje", new object[] {
                        ol});
        }
        
        /// <remarks/>
        public void nyOrdrelinjeAsync(Ordrelinje ol) {
            this.nyOrdrelinjeAsync(ol, null);
        }
        
        /// <remarks/>
        public void nyOrdrelinjeAsync(Ordrelinje ol, object userState) {
            if ((this.nyOrdrelinjeOperationCompleted == null)) {
                this.nyOrdrelinjeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnyOrdrelinjeOperationCompleted);
            }
            this.InvokeAsync("nyOrdrelinje", new object[] {
                        ol}, this.nyOrdrelinjeOperationCompleted, userState);
        }
        
        private void OnnyOrdrelinjeOperationCompleted(object arg) {
            if ((this.nyOrdrelinjeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nyOrdrelinjeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/slettOrdrelinje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void slettOrdrelinje(int ordrelinjeID) {
            this.Invoke("slettOrdrelinje", new object[] {
                        ordrelinjeID});
        }
        
        /// <remarks/>
        public void slettOrdrelinjeAsync(int ordrelinjeID) {
            this.slettOrdrelinjeAsync(ordrelinjeID, null);
        }
        
        /// <remarks/>
        public void slettOrdrelinjeAsync(int ordrelinjeID, object userState) {
            if ((this.slettOrdrelinjeOperationCompleted == null)) {
                this.slettOrdrelinjeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnslettOrdrelinjeOperationCompleted);
            }
            this.InvokeAsync("slettOrdrelinje", new object[] {
                        ordrelinjeID}, this.slettOrdrelinjeOperationCompleted, userState);
        }
        
        private void OnslettOrdrelinjeOperationCompleted(object arg) {
            if ((this.slettOrdrelinjeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.slettOrdrelinjeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOrdrelinjerFraBrukernavn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public List<Ordrelinje> getOrdrelinjerFraBrukernavn(string brukernavn) {
            object[] results = this.Invoke("getOrdrelinjerFraBrukernavn", new object[] {
                        brukernavn});
            return ((List<Ordrelinje>)(results[0]));
        }
        
        /// <remarks/>
        public void getOrdrelinjerFraBrukernavnAsync(string brukernavn) {
            this.getOrdrelinjerFraBrukernavnAsync(brukernavn, null);
        }
        
        /// <remarks/>
        public void getOrdrelinjerFraBrukernavnAsync(string brukernavn, object userState) {
            if ((this.getOrdrelinjerFraBrukernavnOperationCompleted == null)) {
                this.getOrdrelinjerFraBrukernavnOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOrdrelinjerFraBrukernavnOperationCompleted);
            }
            this.InvokeAsync("getOrdrelinjerFraBrukernavn", new object[] {
                        brukernavn}, this.getOrdrelinjerFraBrukernavnOperationCompleted, userState);
        }
        
        private void OngetOrdrelinjerFraBrukernavnOperationCompleted(object arg) {
            if ((this.getOrdrelinjerFraBrukernavnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOrdrelinjerFraBrukernavnCompleted(this, new getOrdrelinjerFraBrukernavnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    /*
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ordrelinje {
        
        private int ordrelinjeIDField;
        
        private int ordreIDField;
        
        private int produktIDField;
        
        private int antallField;
        
        /// <remarks/>
        public int OrdrelinjeID {
            get {
                return this.ordrelinjeIDField;
            }
            set {
                this.ordrelinjeIDField = value;
            }
        }
        
        /// <remarks/>
        public int OrdreID {
            get {
                return this.ordreIDField;
            }
            set {
                this.ordreIDField = value;
            }
        }
        
        /// <remarks/>
        public int ProduktID {
            get {
                return this.produktIDField;
            }
            set {
                this.produktIDField = value;
            }
        }
        
        /// <remarks/>
        public int Antall {
            get {
                return this.antallField;
            }
            set {
                this.antallField = value;
            }
        }
    }
    */
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getOrdrelinjerCompletedEventHandler(object sender, getOrdrelinjerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOrdrelinjerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOrdrelinjerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Ordrelinje[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Ordrelinje[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getOrdrelinjeCompletedEventHandler(object sender, getOrdrelinjeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOrdrelinjeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOrdrelinjeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Ordrelinje Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Ordrelinje)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void nyOrdrelinjeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void slettOrdrelinjeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getOrdrelinjerFraBrukernavnCompletedEventHandler(object sender, getOrdrelinjerFraBrukernavnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOrdrelinjerFraBrukernavnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOrdrelinjerFraBrukernavnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Ordrelinje[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Ordrelinje[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591