//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myApp.ClientDAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:3302/ServerDAL/OrdreDAL.asmx")]
        public string ClientDAL_OrdreDAL_OrdreDAL {
            get {
                return ((string)(this["ClientDAL_OrdreDAL_OrdreDAL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:3302/ServerDAL/OrdrelinjeDAL.asmx")]
        public string ClientDAL_OrdrelinjeDAL_OrdrelinjeDAL {
            get {
                return ((string)(this["ClientDAL_OrdrelinjeDAL_OrdrelinjeDAL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:3302/ServerDAL/ProduktkategoriDAL.asmx")]
        public string ClientDAL_ProduktkategoriDAL_ProduktkategoriDAL {
            get {
                return ((string)(this["ClientDAL_ProduktkategoriDAL_ProduktkategoriDAL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:3302/ServerDAL/AnmeldelseDAL.asmx")]
        public string ClientDAL_AnmeldelseDAL_AnmeldelseDAL {
            get {
                return ((string)(this["ClientDAL_AnmeldelseDAL_AnmeldelseDAL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:3302/ServerDAL/NyhetDAL.asmx")]
        public string ClientDAL_NyhetDAL_NyhetDAL {
            get {
                return ((string)(this["ClientDAL_NyhetDAL_NyhetDAL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:3302/ServerDAL/ProduktDAL.asmx")]
        public string ClientDAL_ProduktDAL_ProduktDAL {
            get {
                return ((string)(this["ClientDAL_ProduktDAL_ProduktDAL"]));
            }
        }
    }
}
