//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.832.
// 
#pragma warning disable 1591

namespace myApp.ClientDAL.WSNyhetDAL {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Collections.Generic;
    using myApp.Model;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServerNyhetDALSoap", Namespace="http://tempuri.org/")]
    public partial class ServerNyhetDAL : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getNyheterOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNyhetOperationCompleted;
        
        private System.Threading.SendOrPostCallback nyNyhetOperationCompleted;
        
        private System.Threading.SendOrPostCallback endreNyhetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServerNyhetDAL() {
            this.Url = global::myApp.ClientDAL.Properties.Settings.Default.MyApp_ClientDAL_WSNyhetDAL_NyhetDAL;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getNyheterCompletedEventHandler getNyheterCompleted;
        
        /// <remarks/>
        public event getNyhetCompletedEventHandler getNyhetCompleted;
        
        /// <remarks/>
        public event nyNyhetCompletedEventHandler nyNyhetCompleted;
        
        /// <remarks/>
        public event endreNyhetCompletedEventHandler endreNyhetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getNyheter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public List<Nyhet> getNyheter() {
            object[] results = this.Invoke("getNyheter", new object[0]);
            return ((List<Nyhet>)(results[0]));
        }
        
        /// <remarks/>
        public void getNyheterAsync() {
            this.getNyheterAsync(null);
        }
        
        /// <remarks/>
        public void getNyheterAsync(object userState) {
            if ((this.getNyheterOperationCompleted == null)) {
                this.getNyheterOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNyheterOperationCompleted);
            }
            this.InvokeAsync("getNyheter", new object[0], this.getNyheterOperationCompleted, userState);
        }
        
        private void OngetNyheterOperationCompleted(object arg) {
            if ((this.getNyheterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNyheterCompleted(this, new getNyheterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getNyhet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Nyhet getNyhet(int nyhetID) {
            object[] results = this.Invoke("getNyhet", new object[] {
                        nyhetID});
            return ((Nyhet)(results[0]));
        }
        
        /// <remarks/>
        public void getNyhetAsync(int nyhetID) {
            this.getNyhetAsync(nyhetID, null);
        }
        
        /// <remarks/>
        public void getNyhetAsync(int nyhetID, object userState) {
            if ((this.getNyhetOperationCompleted == null)) {
                this.getNyhetOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNyhetOperationCompleted);
            }
            this.InvokeAsync("getNyhet", new object[] {
                        nyhetID}, this.getNyhetOperationCompleted, userState);
        }
        
        private void OngetNyhetOperationCompleted(object arg) {
            if ((this.getNyhetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNyhetCompleted(this, new getNyhetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/nyNyhet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void nyNyhet(Nyhet n) {
            this.Invoke("nyNyhet", new object[] {
                        n});
        }
        
        /// <remarks/>
        public void nyNyhetAsync(Nyhet n) {
            this.nyNyhetAsync(n, null);
        }
        
        /// <remarks/>
        public void nyNyhetAsync(Nyhet n, object userState) {
            if ((this.nyNyhetOperationCompleted == null)) {
                this.nyNyhetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnyNyhetOperationCompleted);
            }
            this.InvokeAsync("nyNyhet", new object[] {
                        n}, this.nyNyhetOperationCompleted, userState);
        }
        
        private void OnnyNyhetOperationCompleted(object arg) {
            if ((this.nyNyhetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nyNyhetCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/endreNyhet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void endreNyhet(Nyhet n) {
            this.Invoke("endreNyhet", new object[] {
                        n});
        }
        
        /// <remarks/>
        public void endreNyhetAsync(Nyhet n) {
            this.endreNyhetAsync(n, null);
        }
        
        /// <remarks/>
        public void endreNyhetAsync(Nyhet n, object userState) {
            if ((this.endreNyhetOperationCompleted == null)) {
                this.endreNyhetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnendreNyhetOperationCompleted);
            }
            this.InvokeAsync("endreNyhet", new object[] {
                        n}, this.endreNyhetOperationCompleted, userState);
        }
        
        private void OnendreNyhetOperationCompleted(object arg) {
            if ((this.endreNyhetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.endreNyhetCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    //[ystem.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    
    /*public partial class Nyhet {
        
        private int nyhetsIDField;
        
        private string tittelField;
        
        private string tekstField;
        
        /// <remarks/>
        public int NyhetsID {
            get {
                return this.nyhetsIDField;
            }
            set {
                this.nyhetsIDField = value;
            }
        }
        
        /// <remarks/>
        public string Tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string Tekst {
            get {
                return this.tekstField;
            }
            set {
                this.tekstField = value;
            }
        }
    }*/
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getNyheterCompletedEventHandler(object sender, getNyheterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNyheterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNyheterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Nyhet[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Nyhet[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getNyhetCompletedEventHandler(object sender, getNyhetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNyhetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNyhetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Nyhet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Nyhet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void nyNyhetCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void endreNyhetCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591