<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="handlevogn.aspx.cs" Inherits="handlevogn" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:GridView ID="GridView1" DataSourceID="handlevogn1"  runat="server" DataKeyNames="ProduktID" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" OnRowDeleted="GridView1_RowDeleted" OnRowUpdated="GridView1_RowUpdated">
    <Columns>
        
        <asp:BoundField HeaderText="Varenummer" DataField="ProduktID" ReadOnly="True" />
        <asp:BoundField HeaderText="Varenavn" DataField="Varenavn" ReadOnly="True" />
        <asp:BoundField HeaderText="Antall" DataField="Antall" />
        <asp:BoundField HeaderText="Pris" DataField="Pris" ReadOnly="True" />
        <asp:BoundField HeaderText="Sum" DataField="Sum" ReadOnly="True" />
        
    </Columns>
        <EmptyDataTemplate>
            Handlekurven er tom!
        </EmptyDataTemplate>
    </asp:GridView>
    
    <asp:ObjectDataSource ID="handlevogn1" runat="server" UpdateMethod="endreAntall"  DeleteMethod="slettVareFraHandlevogn" SelectMethod="lagOrdreliste" TypeName="ProfileBinder">
        <DeleteParameters>
            <asp:Parameter Name="ProduktID" Type="Int32"  />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="Antall" Type="Int32" />
            <asp:Parameter Name="ProduktID" Type="Int32" />   
        </UpdateParameters>
    </asp:ObjectDataSource>
    &nbsp;&nbsp;<br />
    Totalsum:
    <asp:Label ID="lblSum" runat="server"></asp:Label><br />
    <br />
    &nbsp; &nbsp;
    <asp:LinkButton ID="LinkButtonSlettHandlekurv" runat="server" OnClick="LinkButtonSlettHandlekurv_Click">Tøm handlekurv</asp:LinkButton>
    &nbsp; &nbsp; &nbsp;<asp:LinkButton ID="LinkButtonKasse" runat="server" OnClick="LinkButtonKasse_Click">Gå til kassen</asp:LinkButton><br />
    &nbsp; &nbsp;&nbsp;<br />
    <br />
   
    <br />
</asp:Content>

