//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.832.
// 
#pragma warning disable 1591

namespace myApp.ClientDAL.WSProduktkategoriDAL {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Collections.Generic;
    using myApp.Model;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProduktkategoriDALSoap", Namespace="http://tempuri.org/")]
    public partial class ProduktkategoriDAL : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback nyProduktkategoriOperationCompleted;
        
        private System.Threading.SendOrPostCallback endreProduktkategoriOperationCompleted;
        
        private System.Threading.SendOrPostCallback getProduktkategorierOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProduktkategoriDAL() {
            this.Url = global::myApp.ClientDAL.Properties.Settings.Default.ClientDAL_ProduktkategoriDAL_ProduktkategoriDAL;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event nyProduktkategoriCompletedEventHandler nyProduktkategoriCompleted;
        
        /// <remarks/>
        public event endreProduktkategoriCompletedEventHandler endreProduktkategoriCompleted;
        
        /// <remarks/>
        public event getProduktkategorierCompletedEventHandler getProduktkategorierCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/nyProduktkategori", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void nyProduktkategori(Produktkategori pk) {
            this.Invoke("nyProduktkategori", new object[] {
                        pk});
        }
        
        /// <remarks/>
        public void nyProduktkategoriAsync(Produktkategori pk) {
            this.nyProduktkategoriAsync(pk, null);
        }
        
        /// <remarks/>
        public void nyProduktkategoriAsync(Produktkategori pk, object userState) {
            if ((this.nyProduktkategoriOperationCompleted == null)) {
                this.nyProduktkategoriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnyProduktkategoriOperationCompleted);
            }
            this.InvokeAsync("nyProduktkategori", new object[] {
                        pk}, this.nyProduktkategoriOperationCompleted, userState);
        }
        
        private void OnnyProduktkategoriOperationCompleted(object arg) {
            if ((this.nyProduktkategoriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nyProduktkategoriCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/endreProduktkategori", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void endreProduktkategori(Produktkategori pk) {
            this.Invoke("endreProduktkategori", new object[] {
                        pk});
        }
        
        /// <remarks/>
        public void endreProduktkategoriAsync(Produktkategori pk) {
            this.endreProduktkategoriAsync(pk, null);
        }
        
        /// <remarks/>
        public void endreProduktkategoriAsync(Produktkategori pk, object userState) {
            if ((this.endreProduktkategoriOperationCompleted == null)) {
                this.endreProduktkategoriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnendreProduktkategoriOperationCompleted);
            }
            this.InvokeAsync("endreProduktkategori", new object[] {
                        pk}, this.endreProduktkategoriOperationCompleted, userState);
        }
        
        private void OnendreProduktkategoriOperationCompleted(object arg) {
            if ((this.endreProduktkategoriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.endreProduktkategoriCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getProduktkategorier", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public List<Produktkategori> getProduktkategorier() {
            object[] results = this.Invoke("getProduktkategorier", new object[0]);
            return ((List<Produktkategori>)(results[0]));
        }
        
        /// <remarks/>
        public void getProduktkategorierAsync() {
            this.getProduktkategorierAsync(null);
        }
        
        /// <remarks/>
        public void getProduktkategorierAsync(object userState) {
            if ((this.getProduktkategorierOperationCompleted == null)) {
                this.getProduktkategorierOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProduktkategorierOperationCompleted);
            }
            this.InvokeAsync("getProduktkategorier", new object[0], this.getProduktkategorierOperationCompleted, userState);
        }
        
        private void OngetProduktkategorierOperationCompleted(object arg) {
            if ((this.getProduktkategorierCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProduktkategorierCompleted(this, new getProduktkategorierCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    /*
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Produktkategori {
        
        private int produktkategoriIDField;
        
        private string navnField;
        
        /// <remarks/>
        public int ProduktkategoriID {
            get {
                return this.produktkategoriIDField;
            }
            set {
                this.produktkategoriIDField = value;
            }
        }
        
        /// <remarks/>
        public string Navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
            }
        }
    }*/
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void nyProduktkategoriCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void endreProduktkategoriCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getProduktkategorierCompletedEventHandler(object sender, getProduktkategorierCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProduktkategorierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProduktkategorierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Produktkategori[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Produktkategori[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591